[project]
name = "instant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.0",
    "fastapi-clerk-auth>=0.0.7",
    "openai>=2.5.0",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
